# Specify the type of chat tool, the value can be mattermost, slack or msteams.
# The default value is mattermost.
chatToolType: slack

# Configure logging
log:
  # Specify the level of logs, the value can be error, warn, info, verbose, debug or silly.
  # The default value is info.
  level: info

  # Specify the maximum size of the file after which it will rotate. The value can be a number of bytes without any unit
  # or a number suffixed with 'k', 'm', or 'g' as units of kb, mb, or gb separately.
  # The default value is null, which means the file size is unlimited except operating system limit.
  maximumSize: null

  # Specify the maximum file number of logs to keep.
  # The default value is null, which means only one log file and no logs will be removed.
  maximumFiles: null

# Specify the maximum number of resources that chatbot can retrieve for you.
recordLimit: 10

# Specify the maximum number of plugins that can respond to the same matched message or event.
pluginLimit: -1

# Specify the functional user id used to access your z/OS system.
userId: <Your user id>

# Specify the password of the functional user.
userPassword: <Your password>
