# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Zowe Chat CI Build

on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize]
    

jobs:
  build-and-test:
    if: (!contains(github.event.head_commit.message, '[ci skip]'))
    runs-on: ${{ matrix.os }}
    outputs:
      npm-resolutions: ${{ steps.npm-update.outputs.result }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]
        os: [ubuntu-latest]

    env:
      OS: ${{ matrix.os }}
      NODE: ${{ matrix.node-version }}

    timeout-minutes: 60

    concurrency:
      group: ${{ matrix.os }}-node-${{ matrix.node-version }}-ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get NPM Version
      id: npm-version
      run: echo "::set-output name=number::$(npm --version)"

    - name: Use NPM v8
      id: npm8
      run: npm install -g npm@~8.3.2

    - name: Install Dependencies
      run: npm ci

    - name: Build Source
      id: build
      run: npm run buildAll

    - name: Unit Tests
      run: npm run test:unit

    - name: Integration Tests
      run: npm run test:integration

    - name: Archive Results
      if: ${{ always() && steps.build.outcome == 'success' }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.node-version }}-results
        path: __tests__/__results__/

    - name: Upload Results to Codecov
      if: ${{ always() && steps.build.outcome == 'success' }}
      uses: codecov/codecov-action@v3
      with:
        env_vars: OS,NODE

  dump-info:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo -e "\033[31;1;4mDump GitHub context\033[0m"
          echo -e "$GITHUB_CONTEXT\n"
        shell: bash
      - name: Dump labels
        run: echo "${{ github.event.pull_request.labels }}" 
      - name: Dump labels
        run: echo "${{ github.ref }}"

  call-deploy-dev:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: 'Call deployment workflow'
        uses: zowe-actions/shared-actions/workflow-remote-call-wait@main
        id: call-deploy-dev-chat
        with:
          github-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}
          owner: zowe
          repo: zowe-chat
          workflow-filename: pr-label-trigger-deploy.yml
          poll-frequency: 3
          branch-name: ${{ github.head_ref }}

  call-deploy-main:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event.name == 'push' && contains(github.ref, 'main')
    steps:
      - name: 'Check if a valid label exists'
        uses: zowe-actions/shared-actions/workflow-remote-call-wait@main
        id: call-deploy-main-chat
        with:
          github-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}
          owner: zowe
          repo: zowe-chat
          workflow-filename: deploy-stable.yml
          branch-name: ${{ github.head_ref }}
          github-ref: ${{ github.ref }} 
          poll-frequency: 3
          inputs-json-string: '{"branch-or-ref":"${{ github.ref }}", "test-server": "$TEST_SERVER", "run-system-test": "false"}'
