name: Deploy Stable Environment

on:
  workflow_dispatch:
    inputs:
      RANDOM_DISPATCH_EVENT_ID:
        description: 'random dispatch event id'
        required: false
        type: string
  push:
    branches:
      - "main"

jobs:
  display-dispatch-event-id:
    if: github.event.inputs.RANDOM_DISPATCH_EVENT_ID != ''
    runs-on: ubuntu-latest
    steps:
    - name: RANDOM_DISPATCH_EVENT_ID is ${{ github.event.inputs.RANDOM_DISPATCH_EVENT_ID }}
      run: echo "prints random dispatch event id sent from workflow dispatch event"
  deploy-chat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: 'zowe/zowe-chat'
        ref: ${{ github.event.inputs.branch-or-ref }}

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Use NPM v8
      id: npm8
      run: npm install -g npm@~8.3.2

    - name: Install Dependencies
      run: npm ci

    - name: Build Source
      id: build
      run: npm run buildAll

    - name: Package Chat
      id: package
      run: npm run packagingAll

    - name: Deploy Stable Environment
      id: deploy-stable
      run: echo 'deploy-stable'
