# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Zowe Chat Deploy - Dev Environment

on:
  workflow_dispatch:
    inputs:
      test-server:
        description: 'Choose the test instance'
        type: choice
        required: true
        options:
        - Dev Instance 1
        - Dev Instance 2
      run-system-test:
        description: 'Run system tests after install'
        type: boolean
        required: true
        default: false
      branch-or-ref:
        description: 'Branch or ref to deploy to test instance'
        type: string
        required: true  

jobs:
  deploy-chat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: 'zowe/zowe-chat'
        ref: ${{ github.event.inputs.branch-or-ref }}

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Use NPM v8
      id: npm8
      run: npm install -g npm@~8.3.2

    - name: Install Dependencies
      run: npm ci

    - name: Build Source
      id: build
      run: npm run buildAll

    - name: Package Chat
      id: Package
      run: npm run packagingAll

    - name: Install Chat Dev-1
      if: contains(github.event.inputs.test-server, "Dev Instance 1")
      run: echo 'dev-1 deploy'

    - name: Install Chat Dev-2
      if: contains(github.event.inputs.test-server, "Dev Instance 2")
      run: echo 'dev-2 deploy'
