permissions: read-all
name: Lint

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Use NPM v8
        id: npm8
        run: npm install -g npm@^8

      - name: Install Node Package Dependencies
        run: npm ci

      - name: Lint
        run: npm run lintAll
